### ISSUE TITLE
mac dmg needs to be rebuilt for later MacOSs? 

### ISSUE THREAD

**Issue by orm011** [TurboVNC/buildscripts#1]
This is on MacOS Mojave 10.14.5
I assume this may be a build config issue, but can also file on the main project issues page.

<img width="410" alt="Screen Shot 2020-01-14 at 8 01 21 PM" src="https://user-images.githubusercontent.com/565364/72395929-07019900-3709-11ea-8a3f-06c6b98edeb8.png">

**Comment by dcommander** [comment]
No, it's the same issue as https://github.com/VirtualGL/virtualgl/issues/104.  Apple started requiring packages to be notarized, but notarization is an offline manual process (you have to submit your package to Apple's servers and then keep checking to see if it is complete), so it isn't a good fit for our automated build scripts.  Until recently, also, I couldn't even test it, because notarization requires Xcode 10, and Xcode 10 requires High Sierra or later.  Since I upgraded to High Sierra, that is no longer a problem, but I haven't had a chance to revisit this issue.  The workaround is to hold down Alt, right-click the package, and select "Open."

**Comment by orm011** [comment]
Ah, notarization sounds painful. Sorry to hear. Thanks for the software.

**Comment by dcommander** [comment]
Yeah, painful indeed.  I'm still looking into how to do it, though, because I don't have a choice.  Once I figure that out, the process will get propagated into libjpeg-turbo, VirtualGL, and TurboVNC (I use the same build and code signing infrastructure for all of them.)

**Comment by dcommander** [comment]
At the moment, notarization is a no-go.  The requirements are just too onerous.  If the Alt-right-click workaround stops working at some point, then I'll be forced to revisit, but honestly, I am going to hold out on this as long as I possibly can, in hopes that Apple streamlines the notarization process.
